# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wrd' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'FSCalendar'
  # Pods for wrd
end
